from pathlib import Path

ROOT = Path(__file__).parent / "tools"
VERSION = "real-data-tools-20260825-r4"

HEADER = '''<header class="site-header"><div class="nav-container"><a href="../index.html" class="logo" aria-label="GugoPro 財經學院首頁"><span class="logo-icon"><i class="fa-solid fa-chart-line"></i></span><span class="logo-copy"><span class="logo-text">GugoPro</span><span class="logo-tag">ACADEMY</span></span></a><nav class="primary-nav" aria-label="主要導覽"><a href="../index.html#knowledge-tree">知識樹</a><a href="index.html">實戰工具</a><a href="../index.html#reading-room">閱讀室</a></nav><div class="nav-actions"><a class="support-link" data-kofi-link href="https://ko-fi.com" target="_blank" rel="noopener noreferrer"><i class="fa-solid fa-mug-hot"></i><span>支持學院</span></a><div class="lang-selector"><button class="lang-btn" type="button"><i class="fa-solid fa-globe"></i><span>繁中</span><i class="fa-solid fa-chevron-down"></i></button><div class="lang-dropdown"><a href="#" onclick="changeLanguage('zh-tw')">繁體中文</a><a href="#" onclick="changeLanguage('zh-cn')">简体中文</a><a href="#" onclick="changeLanguage('en')">English</a></div></div><button class="mobile-nav-toggle" type="button" aria-label="開啟選單" aria-expanded="false"><i class="fa-solid fa-bars"></i></button></div></div></header>'''

FOOTER = '''<section class="resource-strip" data-tradingview-cta aria-label="TradingView 合作資源"><div><span class="sponsor-eyebrow">PARTNER RESOURCE / TRADINGVIEW</span><h2>把真實資料放回圖表驗證</h2><p>使用全球市場圖表、指標腳本與回測工具，交叉檢查工具計算與交易假設。</p></div><a href="https://www.tradingview.com/?aff_id=168714" target="_blank" rel="noopener noreferrer" class="button button-light">領取優惠註冊 <i class="fa-solid fa-arrow-up-right-from-square"></i></a></section><footer class="site-footer"><div class="footer-inner"><div class="footer-brand"><a href="../index.html" class="logo"><span class="logo-icon"><i class="fa-solid fa-chart-line"></i></span><span class="logo-copy"><span class="logo-text">GugoPro</span><span class="logo-tag">ACADEMY</span></span></a><p>把市場雜訊，整理成一條可走的路。</p></div><div class="footer-nav"><div><strong>探索</strong><a href="../guides/taiwan-stocks.html">台股四章節指南</a><a href="index.html">實戰工具庫</a><a href="../index.html#knowledge-tree">13 類知識樹</a></div><div><strong>支持</strong><a data-kofi-link href="https://ko-fi.com" target="_blank" rel="noopener noreferrer">Ko-fi 贊助支持</a><a href="https://www.amazon.com/?tag=9908qq-20" target="_blank" rel="noopener noreferrer">Amazon Hub</a></div><div><strong>政策</strong><a href="/privacy.html">隱私權政策</a><a href="/terms.html">服務條款與免責</a><a href="/about.html">關於我們</a></div></div></div><div class="footer-bottom"><span>© 2026 GugoPro Academy</span><span>教育內容，不構成投資建議。</span></div></footer>'''

OPTIONS = '''<option value="">熱門台股快選</option><option value="2330">2330 · 台積電</option><option value="2454">2454 · 聯發科</option><option value="2603">2603 · 長榮</option><option value="2317">2317 · 鴻海</option><option value="0050">0050 · 元大台灣50</option><option value="0056">0056 · 元大高股息</option><option value="00878">00878 · 國泰永續高股息</option><option value="00919">00919 · 群益台灣精選高息</option>'''


def shell(title, description, chapter, heading, intro, prefix, controls, hud, chart_title, chart_aria, guide_html, result_title):
    script_files = {'tw-inst': 'tw-institutional-tracker.js', 'tw-ma': 'tw-ma-deduction-calculator.js', 'tw-val': 'tw-stock-valuation.js', 'tw-fee': 'tw-day-trading-fee-calc.js'}
    script_file = script_files[prefix]
    secondary_chart = ''
    if prefix == 'tw-val':
        secondary_chart = '<div class="tw-chart-secondary"><span class="section-kicker">DIVIDEND / FILL HISTORY</span><h3>現金股利與填息天數</h3><canvas id="tw-val-dividend-chart" role="img" aria-label="現金股利與填息天數歷史圖"></canvas><p class="tw-chart-caption" id="tw-val-dividend-caption">等待真實資料載入。</p></div>'
    elif prefix == 'tw-ma':
        secondary_chart = '<div class="tw-chart-secondary"><span class="section-kicker">OSCILLATORS / MOMENTUM</span><h3>KD、RSI 與 MACD 指標副圖</h3><canvas id="tw-ma-indicator-chart" role="img" aria-label="KD、RSI 與 MACD 指標副圖"></canvas><p class="tw-chart-caption" id="tw-ma-indicator-caption">等待真實資料載入。</p></div>'
    return f'''<!doctype html>
<html lang="zh-Hant">
<head>
  <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="{description}">
  <title>{title}｜GugoPro 財經學院</title>
  <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Space+Grotesk:wght@500;600;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"><link rel="stylesheet" href="../style.css?v={VERSION}"><link rel="stylesheet" href="advanced-tools.css?v={VERSION}">
</head>
<body class="tools-page tw-tool-page tw-real-data-page">
{HEADER}
<main class="container tw-tool-main">
  <a class="tw-back-link" href="../guides/taiwan-stocks.html#{chapter}"><i class="fa-solid fa-arrow-left"></i> 閱讀完整台股指南：{chapter}</a>
  <section class="tw-tool-hero"><div><div class="tw-real-kicker">{chapter.upper()} / REAL PUBLIC DATA</div><h1>{heading}</h1><p>{intro}</p></div><div class="tw-tool-status" id="{prefix}-status"><span class="tw-status-dot"></span><strong id="{prefix}-status-main">等待載入</strong><small id="{prefix}-status-detail">輸入標的後自動查詢公開資料</small></div></section>
  <section class="tw-real-hud" aria-label="即時量化看板"><div class="tw-control-row"><div class="tw-symbol-control"><label for="{prefix}-symbol">標的搜尋</label><div class="tw-control-inline"><input id="{prefix}-symbol" value="2330" inputmode="numeric" autocomplete="off" aria-describedby="{prefix}-source"><select id="{prefix}-symbol-select" aria-label="熱門台股快選">{OPTIONS}</select><button class="tw-calc-button" type="button" id="{prefix}-load"><i class="fa-solid fa-cloud-arrow-down"></i> 查詢行情</button></div></div>{controls}</div><div class="tw-hud-grid">{hud}</div><p class="tw-source-line" id="{prefix}-source">資料來源：FinMind 公開資料服務；載入後顯示最新查詢時間。</p></section>
  <section class="tw-live-layout"><div class="tw-chart-card"><div class="tw-chart-head"><div><span class="section-kicker">INTERACTIVE CHART</span><h2>{chart_title}</h2></div><span class="tw-live-badge">LIVE DATA</span></div><canvas id="{prefix}-chart" role="img" aria-label="{chart_aria}"></canvas><p class="tw-chart-caption" id="{prefix}-chart-caption">等待真實資料載入。</p>{secondary_chart}</div><aside class="tw-tool-card tw-read-card"><span class="section-kicker">READ THE SIGNAL</span><h2>資料讀法與限制</h2><div class="tw-education-copy">{guide_html.split('</div>')[0].split('<div>')[-1]}</div><p>數值由公開資料端點與瀏覽器計算產生；端點延遲、資料修訂、除權息、流動性與交易制度可能影響解讀。請以原始公告和圖表交叉確認。</p><a href="../guides/taiwan-stocks.html#{chapter}" class="tw-guide-return"><i class="fa-solid fa-book-open"></i> 回到本章完整教學 <i class="fa-solid fa-arrow-right"></i></a></aside></section>
  <section class="tw-tool-result-card" aria-live="polite"><div class="tw-result-head"><div><span class="section-kicker">QUANTITATIVE OUTPUT</span><h2>{result_title}</h2></div><span class="tw-result-badge tw-real-badge">PUBLIC DATA</span></div><div id="{prefix}-result" class="tw-tool-result"><p class="tw-loading"><i class="fa-solid fa-spinner fa-spin"></i> 正在載入公開資料。</p></div></section>
  <section class="tw-bottom-guide" aria-labelledby="{prefix}-guide-title"><div class="tw-bottom-guide-head"><span class="section-kicker">METHOD / FIELD GUIDE</span><h2 id="{prefix}-guide-title">📚 完整指標定義、公式原理與實戰研判教學</h2></div>{guide_html}</section>
  <div class="tw-tool-links"><a href="../guides/taiwan-stocks.html#{chapter}"><i class="fa-solid fa-book-open"></i> 返回本章教學</a><a href="index.html"><i class="fa-solid fa-compass"></i> 瀏覽全部工具</a></div>
  <p class="tool-disclaimer">本頁使用公開市場資料與透明公式，不構成投資建議；行情、費率、稅務、交易資格與法規可能變動，請以交易所、券商、主管機關及資料來源最新公告為準。</p>
</main>
{FOOTER}
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js"></script><script src="../app.js?v={VERSION}"></script><script src="tw-market-data.js?v={VERSION}"></script><script src="{script_file}?v={VERSION}"></script>
</body></html>'''

inst_guide = '''<div><h3>外資、投信與自營商的定義</h3><p>FinMind 的法人資料以買進與賣出股數呈現；工具先按資料分類彙總，再以 1,000 股換算成張。外資可能同時調整現貨、期貨與匯率曝險，投信受基金申贖與持股限制影響，自營商則可能混合自行交易與避險交易。</p><h3>近 5 日與 20 日動能</h3><p>法人淨買賣超公式為：<strong>買進張數 − 賣出張數</strong>。近 5 日、20 日累計是同一公式的時間聚合，適合觀察方向是否延續，不是未來報酬的保證。</p><h3>融資、融券與券資比</h3><p><strong>券資比＝融券餘額 ÷ 融資餘額 × 100%</strong>。工具同時顯示融資／融券日增減；比率升高可能代表回補壓力增加，也可能只是融資下降，必須搭配價格、成交量與可借券狀況。</p><h3>集中度與研判流程</h3><p>工具以本次查詢窗口的單日法人絕對淨流向占比作為波動代理值，並非官方大戶持股統計。實戰先核對資料日期，再看收盤是否站回關鍵位、量能是否支持，最後設定失效條件。</p></div>'''
inst_controls = '<label class="tw-compact-control" for="tw-inst-lookback">查詢日數<select id="tw-inst-lookback"><option value="30">近 30 日</option><option value="60" selected>近 60 日</option><option value="90">近 90 日</option></select></label>'
inst_hud = '<div><span>最新收盤</span><strong id="tw-inst-hud-price">—</strong><small id="tw-inst-hud-date">—</small></div><div><span>外資單日</span><strong id="tw-inst-hud-foreign">—</strong><small id="tw-inst-hud-foreign-detail">張／金額</small></div><div><span>投信單日</span><strong id="tw-inst-hud-trust">—</strong><small id="tw-inst-hud-trust-detail">張／金額</small></div><div><span>自營商單日</span><strong id="tw-inst-hud-dealer">—</strong><small id="tw-inst-hud-dealer-detail">張／金額</small></div><div><span>法人單日合計</span><strong id="tw-inst-hud-day">—</strong><small id="tw-inst-hud-symbol">—</small></div><div><span>近 5 日動能</span><strong id="tw-inst-hud-5d">—</strong><small>張</small></div><div><span>近 20 日動能</span><strong id="tw-inst-hud-20d">—</strong><small>張</small></div><div><span>投信連買</span><strong id="tw-inst-hud-streak">—</strong><small>日</small></div><div><span>券資比</span><strong id="tw-inst-hud-ratio">—</strong><small>融券／融資</small></div><div><span>融資日增減</span><strong id="tw-inst-hud-margin">—</strong><small>張</small></div><div><span>融券日增減</span><strong id="tw-inst-hud-short">—</strong><small>張</small></div><div><span>流向集中代理</span><strong id="tw-inst-hud-concentration">—</strong><small>窗口占比</small></div>'
inst_page = shell('三大法人與籌碼歷史分析儀', '自動抓取台股價格、三大法人、融資融券公開資料，計算 5 日／20 日動能與券資比。', 'chips-analysis', '三大法人與籌碼歷史分析儀', '輸入台股代號，查詢公開歷史資料，將法人買賣超、融資融券與價格走勢放在同一張分析畫面。', 'tw-inst', inst_controls, inst_hud, '法人流向、價格與融資融券歷史圖', '收盤價格與三大法人每日買賣超歷史圖', inst_guide, '法人動能與籌碼條件')

ma_guide = '''<div><h3>均線扣抵的數學原理</h3><p>以 N 日均線為例：<strong>今日 MA＝（前一日 MA × N − 被扣除的舊收盤＋今日新收盤）÷ N</strong>。當預計加入的收盤高於被扣除價格，均線有上推壓力，稱為扣低助漲；反之為扣高助跌。工具以已抓到的真實日 K 向前移動，沒有用假價格填補未來。</p><h3>5MA、20MA、60MA 與量能</h3><p>短均線對價格反應快，長均線用來辨識背景趨勢。量能倍數為：<strong>最新成交量 ÷ 近 20 日平均成交量</strong>；放量突破需要觀察是否站穩，窒息量則要搭配價格位置，不可單獨下結論。</p><h3>RSI、KD 與 MACD</h3><p>RSI 以近 14 期漲跌計算相對強弱，KD 以 9 期區間位置觀察收盤，MACD 比較 12 期與 26 期 EMA。指標鈍化表示價格沿趨勢運行時可能長時間停留高檔或低檔，實戰應加入價格結構、成交量與失效點。</p><h3>扣抵研判流程</h3><p>先確認最新收盤、5MA／20MA／60MA 相對位置，再查看接下來 3 日被扣除價位，最後用成交量和回踩是否守住來驗證，而不是把「助漲／助跌」直接當成交易訊號。</p></div>'''
ma_controls = '<label class="tw-compact-control" for="tw-ma-horizon">前瞻日數<select id="tw-ma-horizon"><option value="1">1 日</option><option value="2">2 日</option><option value="3" selected>3 日</option></select></label>'
ma_hud = '<div><span>最新收盤</span><strong id="tw-ma-hud-price">—</strong><small id="tw-ma-hud-date">—</small><small id="tw-ma-hud-symbol">—</small></div><div><span>5MA</span><strong id="tw-ma-hud-5">—</strong><small>短均線</small></div><div><span>20MA</span><strong id="tw-ma-hud-20">—</strong><small>月線代理</small></div><div><span>60MA</span><strong id="tw-ma-hud-60">—</strong><small>季線代理</small></div><div><span>今日扣抵 5／20</span><strong id="tw-ma-hud-deduct">—</strong><small>價格</small></div><div><span>量能倍數</span><strong id="tw-ma-hud-volume">—</strong><small>相對 20 日均量</small></div><div><span>RSI(14)</span><strong id="tw-ma-hud-rsi">—</strong><small>相對強弱</small></div><div><span>K／D(9)</span><strong id="tw-ma-hud-kd">—</strong><small>隨機指標</small></div><div><span>MACD(12,26)</span><strong id="tw-ma-hud-macd">—</strong><small>動能差</small></div>'
ma_page = shell('均線扣抵、量價結構與指標診斷儀', '自動抓取台股日 K 與成交量，計算 5MA、20MA、60MA、扣抵、RSI、KD 與 MACD。', 'technical-analysis', '均線扣抵、量價結構與指標診斷儀', '輸入台股代號，查詢真實日 K 與成交量，檢視 5MA／20MA／60MA、扣抵位置、量能倍數與技術指標。', 'tw-ma', ma_controls, ma_hud, '台股日 K、均線與成交量', '台股收盤價、5MA、20MA 與成交量互動圖', ma_guide, '均線扣抵與量價指標')

val_guide = '''<div><h3>本益比河流圖怎麼讀</h3><p>工具抓取歷史公開 PER，將 P10、P50、P90 作為歷史分位參考，再以近四季 EPS 換算價格帶：<strong>參考價＝EPS × 歷史 PE 分位數</strong>。分位帶反映市場曾經給過的估值範圍，不代表內在價值或目標價。</p><h3>PEG 與成長口徑</h3><p>PEG 公式為：<strong>PE ÷ EPS 年增率（百分點）</strong>。工具以近四季 EPS 的可用資料推算年化變化；若 EPS 不足，會顯示資料限制，不以手動假設補齊。跨景氣循環比較時，應檢查基期、一次性損益與產業週期。</p><h3>除息參考價與填息天數</h3><p>除息參考價可用：<strong>除息前收盤價 − 現金股利</strong>。工具從股利資料的除息日往後尋找首次回到除息前收盤價的交易日，估算填息天數；沒有足夠行情時顯示資料不足，不把估算變成機率保證。</p><h3>實戰風險檢核</h3><p>先核對最新 PER、近 12 個月現金殖利率與歷史分位，再檢查獲利品質、股利政策、除息缺口與價格位階。高殖利率可能反映景氣循環或價格下跌，不能只看單一指標。</p></div>'''
val_controls = '<span class="tw-period-note">歷史視窗：近 3 年公開 PER／股利／財報資料</span>'
val_hud = '<div><span>最新收盤</span><strong id="tw-val-hud-price">—</strong><small id="tw-val-hud-date">—</small><small id="tw-val-hud-symbol">—</small></div><div><span>最新 P/E</span><strong id="tw-val-hud-pe">—</strong><small>公開 PER</small></div><div><span>現金殖利率</span><strong id="tw-val-hud-yield">—</strong><small>近 12 個月代理</small></div><div><span>平均填息天數</span><strong id="tw-val-hud-fill">—</strong><small>除息後估算</small></div><div class="tw-hud-wide"><span>歷史 PE 價格帶</span><strong id="tw-val-hud-band">—</strong><small>P10 至 P90</small></div>'
val_page = shell('本益比河流圖、成長估值與除權息試算儀', '自動抓取台股股價、歷史 PER、財報 EPS 與股利資料，繪製 PE 分位估值帶與填息趨勢。', 'fundamentals-analysis', '本益比河流圖、成長估值與除權息試算儀', '輸入台股代號，查詢公開股價、PER、財報 EPS 與股利，建立歷史估值帶、PEG、殖利率與填息天數。', 'tw-val', val_controls, val_hud, '歷史 PE 分位與股利／填息圖', '歷史本益比河流圖與現金股利填息趨勢圖', val_guide, '歷史估值與股利分析')

fee_guide = '''<div><h3>交易成本公式</h3><p>台股買賣手續費通常以成交金額乘券商牌告費率與折讓估算；工具以 0.1425% × 折數計算，並套用每邊最低 20 元防呆。證交稅以賣出成交金額計算，支援現股 0.3%、現股當沖 0.15%、ETF 0.1% 三種選擇。</p><h3>損益平衡與 Tick</h3><p>成本後損益＝毛損益 − 買賣手續費 − 證交稅 − 借券／資金成本；損益平衡賣價則反解成本後淨損益為零的價格。工具依台股價格級距估算最小跳動檔位，讓結果以實際報價精度呈現。</p><h3>T+2 與融資／借券成本</h3><p>若現股當沖沒有完成反向成交，買進金額與費用可能需要在 T+2 準備；工具以買進成交金額加買進手續費作為應備資金壓力測試。借券／資金成本＝成交金額 × 年率 × 天數 ÷ 365，實際費率與資格以券商合約為準。</p><h3>部位風控</h3><p>風險股數上限＝可承擔資金 × 單筆風險比例 ÷ 每股停損距離。當沖資格、借券可得性、滑價、漲跌幅與逐筆撮合都可能使理論結果與實際成交不同，提交委託前要再確認。</p></div>'''
fee_controls = '<label class="tw-compact-control" for="tw-fee-mode">交易稅制<select id="tw-fee-mode"><option value="day">現股當沖 · 0.15%</option><option value="cash">一般現股 · 0.3%</option><option value="etf">ETF · 0.1%</option></select></label>'
fee_hud = '<div><span>最新收盤</span><strong id="tw-fee-hud-price">—</strong><small id="tw-fee-hud-date">—</small></div><div><span>委託買價</span><strong id="tw-fee-hud-buy">—</strong><small>可自行調整</small></div><div><span>交易 Tick</span><strong id="tw-fee-hud-tick">—</strong><small>價格級距</small></div><div><span>證交稅率</span><strong id="tw-fee-hud-tax">—</strong><small id="tw-fee-hud-symbol">—</small></div><div><span>預估 ROI</span><strong id="tw-fee-hud-roi">—</strong><small>扣除成本後</small></div>'
fee_controls += '<div class="tw-order-controls"><label for="tw-fee-buy">買進價<input id="tw-fee-buy" type="number" min="0.01" step="0.01" placeholder="載入後自動帶入"></label><label for="tw-fee-sell">賣出價<input id="tw-fee-sell" type="number" min="0.01" step="0.01" placeholder="載入後自動帶入"></label><label for="tw-fee-shares">股數<input id="tw-fee-shares" type="number" min="1" value="1000"></label><label for="tw-fee-discount">手續費折數<select id="tw-fee-discount"><option value="1">1 折</option><option value="2.8" selected>2.8 折</option><option value="3.8">3.8 折</option><option value="6">6 折</option></select></label><label for="tw-fee-borrow">年成本 %<input id="tw-fee-borrow" type="number" min="0" step="0.01" value="0.5"></label><label for="tw-fee-days">天數<input id="tw-fee-days" type="number" min="0" value="2"></label><label for="tw-fee-capital">可用資金<input id="tw-fee-capital" type="number" min="0" value="500000"></label><label for="tw-fee-risk">單筆風險 %<input id="tw-fee-risk" type="number" min="0.1" step="0.1" value="1"></label><label for="tw-fee-stop">停損價<input id="tw-fee-stop" type="number" min="0.01" step="0.01" placeholder="載入後自動帶入"></label></div>'
fee_page = shell('台股交易成本、現股當沖損益與風控試算機', '自動抓取台股最新公開收盤價，計算手續費、證交稅、ROI、Tick、T+2 應備資金與風險股數。', 'trading-rules', '台股交易成本、現股當沖損益與風控試算機', '輸入台股代號後自動帶入最新公開收盤價，再調整委託價格、股數與風控參數，檢查交易成本與交割壓力。', 'tw-fee', fee_controls, fee_hud, '交易成本與損益結構', '手續費、證交稅與借券／資金成本分解圖', fee_guide, '交易成本與執行風控')

files = {
    'tw-institutional-tracker.html': inst_page,
    'tw-ma-deduction-calculator.html': ma_page,
    'tw-stock-valuation.html': val_page,
    'tw-day-trading-fee-calc.html': fee_page,
}
for name, text in files.items():
    (ROOT / name).write_text(text, encoding='utf-8')
print('wrote', ', '.join(files))
