"""第 02–13 類章節工具的單一規格來源。

公開行情工具只接受 ticker 並從頁面標示的端點取得真實資料；數學工具的數值欄位預設為空，要求使用者輸入自己的交易、部位、基金、債券或房產條件，不產生虛構行情。
"""


def text(id_, label, value='', placeholder='輸入代號'):
    return {'id': id_, 'label': label, 'type': 'text', 'value': value, 'placeholder': placeholder}


def number(id_, label, placeholder='輸入你的實際數值', step='0.01'):
    return {'id': id_, 'label': label, 'type': 'number', 'value': '', 'placeholder': placeholder, 'step': step}


def select(id_, label, options):
    return {'id': id_, 'label': label, 'type': 'select', 'options': options}


def checkbox(id_, label):
    return {'id': id_, 'label': label, 'type': 'checkbox'}


def T(id_, file, guide, chapter, category, label, title, description, kicker, kind, controls, hud, read, formula, source):
    return dict(id=id_, file=file, guide=guide, chapter=chapter, category=category, label=label, title=title,
                description=description, kicker=kicker, kind=kind, controls=controls, hud=hud,
                read=read, formula=formula, source=source)


TOOLS = [
    T('us-market-structure', 'us-market-structure.html', 'us-stocks.html', 'us-stocks-foundation', 'us', '市場結構',
      '美股市場結構與指數曝險分析儀', '以公開日線拆解個股／ETF 的趨勢、均線、波動與回撤，避免把指數當成單一股票。',
      '02 US EQUITIES / FOUNDATION', 'yahoo-structure',
      [text('us-structure-symbol', '公開標的代號', 'SPY', '例如 SPY、QQQ、NVDA')],
      ['最新收盤', '50 日均線', '200 日均線', '最大回撤'],
      '使用 Yahoo 公開日線建立價格、50／200 日均線、年化波動與歷史回撤。這是價格資料研究，不代表完整含息報酬或未來趨勢。',
      '均線＝最近 n 個收盤的算術平均；最大回撤＝目前或歷史低點相對前高的最大跌幅；年化波動＝日報酬標準差 × √252。',
      'Yahoo Finance chart 公開歷史行情'),
    T('us-valuation-sensitivity', 'us-valuation-sensitivity.html', 'us-stocks.html', 'us-stocks-metrics', 'us', '估值敏感度',
      '美股 FCF／DCF 敏感度與安全邊際工具', '輸入你查證過的自由現金流、成長、折現率與股本，查看每股價值對假設的敏感度。',
      '02 US EQUITIES / METRICS', 'dcf-sensitivity',
      [number('us-dcf-fcf', '目前年度 FCF'), number('us-dcf-growth', '預測成長率 %'), number('us-dcf-discount', '折現率 %'), number('us-dcf-terminal', '終值成長率 %'), number('us-dcf-years', '預測年數', step='1'), number('us-dcf-shares', '流通股數'), number('us-dcf-price', '目前股價')],
      ['每股理論值', '安全邊際價', '現價差距', '終值占比'],
      'DCF 只是一組假設的現值模型。請從申報文件或公司 IR 填入 FCF 與股本；工具不自動抓取或編造公司預測，並把終值依賴度單獨列出。',
      '企業價值＝各期 FCF 折現值＋終值折現值；每股價值＝企業價值÷流通股數；安全邊際價＝理論值×(1−安全邊際)，本頁安全邊際固定顯示 20% 的教育檢查。',
      '使用者查證的公司財報／IR；公式為透明 DCF'),
    T('us-event-risk-planner', 'us-event-risk-planner.html', 'us-stocks.html', 'us-stocks-practice', 'us', '財報事件風控',
      '美股財報事件跳空與部位風控規劃器', '用你的進場、停損、持倉與可承受跳空假設，估算財報前後的最大損失，而不是預測財報方向。',
      '02 US EQUITIES / PRACTICE', 'event-risk',
      [number('us-event-capital', '帳戶資金'), number('us-event-entry', '進場價'), number('us-event-stop', '停損價'), number('us-event-position', '持有股數', step='1'), number('us-event-gap', '壓力跳空幅度 %'), number('us-event-cost', '滑價與費用 %')],
      ['停損名目損失', '跳空壓力損失', '占帳戶比例', '失效距離'],
      '財報、指引與監管事件可能造成盤前或盤後跳空，停損不保證成交價。請填入你的真實部位與保守壓力幅度，工具只做損失預算。',
      '停損損失＝|進場−停損|×股數；跳空損失＝進場×壓力幅度×股數＋成本；風險占比＝損失÷帳戶資金。',
      '使用者自己的交易計畫；事件日期應回查公司 IR／SEC'),
    T('us-currency-return', 'us-currency-return.html', 'us-stocks.html', 'us-stocks-risk', 'us', '美元換算',
      '美股原幣／台幣報酬換算與匯率壓力工具', '把美元股票報酬與 USD/TWD 匯率效果拆開，讓跨境投資人看見真正的本幣結果。',
      '02 US EQUITIES / RISK', 'currency-return',
      [number('us-fx-capital', '原始台幣投入'), number('us-fx-asset-return', '美元資產報酬 %'), number('us-fx-start', '期初 USD/TWD'), number('us-fx-end', '期末 USD/TWD'), number('us-fx-cost', '換匯與交易成本 %')],
      ['美元資產報酬', '匯率效果', '台幣合併報酬', '台幣損益'],
      '台幣投資報酬同時受到美元資產與美元兌台幣變化影響。請填入你的實際換匯與交易紀錄；匯率方向必須維持 USD/TWD 的一致口徑。',
      '台幣合併報酬＝(1＋資產報酬)×(期初匯率÷期末匯率−1 的方向需依報價確認)；本工具以台幣價值＝美元期末資產×期末 USD/TWD，從投入台幣直接重建。',
      '使用者銀行／券商成交紀錄與可查證匯率'),

    T('etf-exposure-audit', 'etf-exposure-audit.html', 'etf.html', 'etf-foundation', 'etf', '曝險集中度',
      'ETF 成分權重與集中度檢查器', '輸入公開說明書或月報中的成分權重，計算前十大集中度與 HHI，檢查分散是否只是名稱印象。',
      '03 ETF / FOUNDATION', 'weight-audit',
      [number('etf-w1', '成分 1 權重 %'), number('etf-w2', '成分 2 權重 %'), number('etf-w3', '成分 3 權重 %'), number('etf-w4', '成分 4 權重 %'), number('etf-w5', '成分 5 權重 %'), number('etf-wrest', '其餘成分合計 %')],
      ['權重合計', '前五大集中', 'HHI', '最大單一權重'],
      '成分權重必須來自該 ETF 最新月報、基金網站或公開說明書。本工具不替你抓取或假設成分，避免把過期權重當成即時事實。',
      '前五大集中＝前五項權重總和；HHI＝各權重小數平方後加總×10,000；權重合計應接近 100%。',
      'ETF 發行人月報／公開說明書'),
    T('etf-fee-drag', 'etf-fee-drag.html', 'etf.html', 'etf-metrics', 'etf', '費用複利',
      'ETF 費用率複利拖累與追蹤差工具', '用你的本金、毛報酬、費用率與持有期間，量化年度費率對終值的長期拖累。',
      '03 ETF / METRICS', 'fee-drag',
      [number('etf-fee-principal', '投入本金'), number('etf-fee-return', '預期毛報酬 %'), number('etf-fee-a', '產品 A 費用 %'), number('etf-fee-b', '產品 B 費用 %'), number('etf-fee-years', '持有年數', step='1')],
      ['A 期末資產', 'B 期末資產', '費用差距', '年化淨報酬差'],
      '這是費用敏感度模型，不是基金報酬承諾。請以基金公開揭露的總費用、追蹤差異與稅費口徑填寫，並將結果與實際資料交叉核對。',
      '期末資產＝本金×(1＋毛報酬−費用率)^年數；費用差距不等於基金完整追蹤差。',
      '基金公開說明書／月報；複利公式'),
    T('etf-rebalance-band', 'etf-rebalance-band.html', 'etf.html', 'etf-practice', 'etf', '再平衡帶',
      'ETF 目標權重與再平衡差額工具', '輸入目前資產與目標權重，計算每一類需要買入或減碼的金額，支援以區間帶管理交易頻率。',
      '03 ETF / PRACTICE', 'allocation-rebalance',
      [number('etf-reb-stock', '股票目前金額'), number('etf-reb-bond', '債券目前金額'), number('etf-reb-cash', '現金目前金額'), number('etf-reb-stock-target', '股票目標 %'), number('etf-reb-bond-target', '債券目標 %'), number('etf-reb-cash-target', '現金目標 %'), number('etf-reb-band', '允許偏離帶 %')],
      ['組合總額', '股票調整額', '債券調整額', '超出再平衡帶'],
      '再平衡不是追逐近期績效。請填入你的實際帳戶金額與事先決定的目標權重；交易成本、稅務與最小下單單位需另行核對。',
      '目標金額＝組合總額×目標權重；調整額＝目標金額−目前金額；偏離帶以目前權重和目標權重差異判斷。',
      '使用者帳戶紀錄與基金目標權重'),
    T('etf-duration-stress', 'etf-duration-stress.html', 'etf.html', 'etf-risk', 'etf', '債券 ETF 壓力',
      '債券 ETF 久期與利差壓力測試器', '輸入債券 ETF 的市值、有效久期、利率與信用利差衝擊，估算價格敏感度與資產影響。',
      '03 ETF / RISK', 'duration-stress',
      [number('etf-stress-value', '部位市值'), number('etf-stress-duration', '有效久期'), number('etf-stress-rate', '利率衝擊 bp'), number('etf-stress-spread', '信用利差衝擊 bp'), number('etf-stress-spread-duration', '利差久期')],
      ['利率價格變化', '信用價格變化', '合計壓力損失', '壓力後市值'],
      '債券 ETF 沒有到期保本；有效久期、信用配置、折溢價與再平衡都會影響實際結果。請用基金月報中的久期或自己的風險假設，不使用預設行情。',
      'ΔP/P≈−利率久期×Δy−利差久期×Δspread；bp 需換成小數。凸性、流動性與匯率未納入線性近似。',
      '基金月報的有效久期／信用資料；Duration 近似公式'),

    T('bond-cashflow-ladder', 'bond-cashflow-ladder.html', 'bonds.html', 'bonds-foundation', 'fixed', '現金流梯形',
      '債券現金流與到期梯形規劃器', '輸入最多五筆債券的面額、票息與到期年數，檢查每年現金流與本金回收是否對應資金用途。',
      '04 FIXED INCOME / FOUNDATION', 'bond-ladder',
      [number('bond-ladder-face1', '債券 1 面額'), number('bond-ladder-coupon1', '債券 1 票息 %'), number('bond-ladder-year1', '債券 1 到期年', step='1'), number('bond-ladder-face2', '債券 2 面額'), number('bond-ladder-coupon2', '債券 2 票息 %'), number('bond-ladder-year2', '債券 2 到期年', step='1'), number('bond-ladder-face3', '債券 3 面額'), number('bond-ladder-coupon3', '債券 3 票息 %'), number('bond-ladder-year3', '債券 3 到期年', step='1')],
      ['年票息現金流', '最近到期年', '五年本金', '平均票息率'],
      '梯形配置的重點是把到期本金與支出時間對齊，不是追求最高票息。請從持倉明細填入實際面額、票息和到期日；價格、稅費與違約風險要另行研究。',
      '年票息＝面額×票面利率；本金回收依到期年歸集；平均票息率＝年票息÷面額總和。',
      '使用者持倉明細／債券發行文件'),
    T('bond-duration-convexity', 'bond-duration-convexity.html', 'bonds.html', 'bonds-metrics', 'fixed', 'Duration 與凸性',
      '債券價格、修正久期與凸性近似計算器', '以你查證的票息、YTM、年期與付息頻率計算價格、久期及利率變動後的近似價格。',
      '04 FIXED INCOME / METRICS', 'bond-pricing',
      [number('bond-price-face', '面額'), number('bond-price-coupon', '票面利率 %'), number('bond-price-ytm', '到期殖利率 %'), number('bond-price-years', '到期年數', step='1'), number('bond-price-frequency', '每年付息次數', step='1'), number('bond-price-shift', '殖利率變動 bp')],
      ['理論價格', 'Macaulay 久期', '修正久期', '壓力後價格'],
      '固定票息不等於固定市值。工具使用完整現值和一階久期近似；大幅利率變化、信用利差與可贖回條款會使結果偏離。',
      'P＝Σ C/(1+y/m)^t＋F/(1+y/m)^n；Modified Duration＝Macaulay/(1+y/m)；ΔP/P≈−Modified Duration×Δy。',
      '使用者債券條款；固定收益現值與久期公式'),
    T('bond-ladder-builder', 'bond-ladder-builder.html', 'bonds.html', 'bonds-practice', 'fixed', '期限配置',
      '債券期限與再投資需求配對器', '把未來五年的實際資金需求與債券到期本金輸入同一張表，找出期限缺口與再投資暴露。',
      '04 FIXED INCOME / PRACTICE', 'bond-needs',
      [number('bond-need1', '第 1 年資金需求'), number('bond-maturity1', '第 1 年到期本金'), number('bond-need2', '第 2 年資金需求'), number('bond-maturity2', '第 2 年到期本金'), number('bond-need3', '第 3 年資金需求'), number('bond-maturity3', '第 3 年到期本金'), number('bond-need4', '第 4 年資金需求'), number('bond-maturity4', '第 4 年到期本金'), number('bond-need5', '第 5 年資金需求'), number('bond-maturity5', '第 5 年到期本金')],
      ['五年總缺口', '最大單年缺口', '到期覆蓋率', '最早缺口年'],
      '期限配對要以實際支出和到期現金流為核心。缺口不是自動的買賣指令，還要加入票息、稅費、通膨與流動性緩衝。',
      '各年缺口＝資金需求−到期本金；總缺口只加總正值；到期覆蓋率＝到期本金總和÷需求總和。',
      '使用者現金流計畫／債券持倉明細'),
    T('bond-credit-stress', 'bond-credit-stress.html', 'bonds.html', 'bonds-risk', 'fixed', '信用壓力',
      '債券利率、信用利差與流動性壓力測試器', '把利率久期、信用久期、流動性折價與部位市值放在同一個壓力框架中。',
      '04 FIXED INCOME / RISK', 'bond-risk',
      [number('bond-risk-value', '部位市值'), number('bond-risk-rate-duration', '利率久期'), number('bond-risk-credit-duration', '信用久期'), number('bond-risk-rate-shock', '利率衝擊 bp'), number('bond-risk-credit-shock', '利差衝擊 bp'), number('bond-risk-liquidity', '流動性折價 %')],
      ['利率損失', '信用損失', '流動性損失', '壓力後市值'],
      '公債、公司債、高收益債與債券 ETF 的風險來源不同。請以持倉報告中的市值和久期填入，結果是線性教育壓力測試，不是違約概率。',
      '壓力損失＝市值×(利率久期×利率衝擊＋信用久期×利差衝擊＋流動性折價)；忽略凸性與相關性。',
      '使用者持倉／基金月報；Duration 壓力公式'),

    T('fund-exposure-compare', 'fund-exposure-compare.html', 'funds.html', 'funds-foundation', 'funds', '基金曝險比較',
      '基金與 ETF 公開價格曝險比較儀', '抓取兩個公開代號的歷史價格，並列比較累積報酬、波動、回撤與相對路徑。',
      '05 FUNDS / STRUCTURE', 'yahoo-compare',
      [text('fund-compare-a', '產品 A', 'VTI', '例如 VTI、BND'), text('fund-compare-b', '產品 B', 'SPY', '例如 SPY、QQQ')],
      ['A 年化報酬', 'B 年化報酬', 'A／B 波動', 'A／B 相關'],
      '公開價格比較不等於完整基金投資人報酬；配息、費用、匯率、申贖與持股曝險應回到基金文件核對。',
      '日報酬、年化波動、累積價格報酬與相關係數使用相同期間和相同頻率計算。',
      'Yahoo Finance chart 公開歷史行情；基金月報補充曝險'),
    T('fund-fee-impact', 'fund-fee-impact.html', 'funds.html', 'funds-metrics', 'funds', '基金費用',
      '共同基金費用、績效費與複利影響試算器', '輸入基金 A／B 的實際費率、申贖費與本金，計算扣費後的資產路徑。',
      '05 FUNDS / METRICS', 'fund-fee',
      [number('fund-fee-principal', '投入本金'), number('fund-fee-return', '毛報酬 %'), number('fund-fee-a', 'A 年費率 %'), number('fund-fee-b', 'B 年費率 %'), number('fund-fee-entry', '一次性申購費 %'), number('fund-fee-years', '持有年數', step='1')],
      ['A 期末資產', 'B 期末資產', '費用差距', '扣費後差距 %'],
      '請依基金公開說明書填入總費用、申購／贖回費與績效費口徑；不要把單一經理費當成完整成本。',
      '期末資產＝本金×(1−申購費)×(1＋毛報酬−年費率)^年數；未含稅務、交易成本與費率變動。',
      '基金公開說明書／費用表'),
    T('fund-due-diligence', 'fund-due-diligence.html', 'funds.html', 'funds-practice', 'funds', '基金盡職檢查',
      '基金 mandate、經理團隊與流動性檢查表', '逐項勾選你已查證的基金資料，將「看過績效」改成可稽核的投資流程。',
      '05 FUNDS / DUE DILIGENCE', 'checklist',
      [checkbox('fund-check-mandate', '已讀公開說明書的投資目標與限制'), checkbox('fund-check-benchmark', '已確認適當 benchmark 與貨幣口徑'), checkbox('fund-check-fee', '已核對總費用、申贖費與績效費'), checkbox('fund-check-holdings', '已查看最新持股、集中度與現金部位'), checkbox('fund-check-manager', '已查證經理團隊任期與策略變更'), checkbox('fund-check-liquidity', '已確認申贖日、入帳時間與流動性'), checkbox('fund-check-distribution', '已區分配息來源與總報酬'), checkbox('fund-check-drawdown', '已檢查完整週期回撤與壓力情境')],
      ['已完成項目', '完成率', '最低門檻', '未完成項目'],
      '這是資料完整度檢查，不是基金評級。未勾選的項目要回到基金公司、公開說明書或月報查證，不以模型分數替代研究。',
      '完成率＝已完成項目÷8；本工具以 75% 作為「可進一步研究」門檻，不代表買進評等。',
      '基金公開說明書／月報／基金公司 IR'),
    T('fund-benchmark-tracking', 'fund-benchmark-tracking.html', 'funds.html', 'funds-risk', 'funds', '基準追蹤差',
      '基金與基準追蹤差、主動風險分析儀', '抓取基金／ETF 與基準的公開價格，估算相對報酬、tracking error 與回撤差異。',
      '05 FUNDS / RISK', 'yahoo-tracking',
      [text('fund-track-a', '基金／ETF 代號', 'VTI', '例如 VTI、BND'), text('fund-track-b', '基準代號', 'SPY', '例如 SPY、AGG')],
      ['基金年化報酬', '基準年化報酬', '相對報酬', 'Tracking error'],
      '公開價格可能沒有完整配息或相同估值時間；tracking error 必須在同一期間、頻率、幣別與調整口徑下解讀。',
      'Tracking error＝相對日報酬標準差×√252；相對報酬＝基金價格報酬−基準價格報酬。',
      'Yahoo Finance chart；基金官方基準定義'),

    T('forex-pip-value', 'forex-pip-value.html', 'forex.html', 'forex-foundation', 'forex', 'Pip 點值',
      '外匯 Pip、點值與停損損益計算器', '輸入貨幣對報價、名目單位、Pip size 與停損距離，計算一筆交易的點值與風險。',
      '06 FX / QUOTE ANATOMY', 'pip-value',
      [number('fx-pip-units', '名目單位'), number('fx-pip-size', 'Pip size', '例如 0.0001'), number('fx-pip-rate', '報價匯率'), number('fx-pip-stop', '停損 Pip 數'), number('fx-pip-cost', '每筆成本（報價幣）')],
      ['每 Pip 點值', '停損名目損失', '含成本損失', '損失占名目 %'],
      '不同貨幣對的小數位與帳戶結算幣別會改變點值。請填入交易商實際報價與合約單位，並另外核對 spread、swap 和滑價。',
      '報價幣點值＝名目單位×Pip size；停損損失＝點值×停損 Pip＋成本。若帳戶幣別不同，還需按即期匯率換算。',
      '使用者交易商報價／合約規格'),
    T('forex-carry-budget', 'forex-carry-budget.html', 'forex.html', 'forex-carry', 'forex', 'Carry 預算',
      '外匯利差、Swap 成本與持有預算工具', '輸入實際兩國利率代理、名目部位、持有天數與交易商費用，檢查利差收益是否值得匯率尾部風險。',
      '06 FX / CARRY & SWAP', 'carry-budget',
      [number('fx-carry-notional', '名目部位'), number('fx-carry-base', '持有貨幣年利率 %'), number('fx-carry-quote', '融資貨幣年利率 %'), number('fx-carry-days', '持有天數', step='1'), number('fx-carry-cost', '交易商／展期成本 %'), number('fx-carry-shock', '匯率壓力變動 %')],
      ['毛利差收益', '費後 Carry', '匯率壓力損失', '淨壓力結果'],
      '政策利率差不是券商實際 swap 報價；請用你的 long／short swap、展期天數和匯率壓力假設，將 carry 與尾部風險放在同一張表。',
      '毛利差收益＝名目部位×(持有貨幣利率−融資貨幣利率)×天數/360；壓力損失＝名目部位×匯率壓力；淨結果＝費後 Carry−壓力損失。',
      '使用者交易商 swap／央行利率文件；公式為教育近似'),
    T('forex-hedge-ratio', 'forex-hedge-ratio.html', 'forex.html', 'forex-hedging', 'forex', '避險比例',
      '外幣資產避險比例與成本工具', '輸入外幣資產、未來外幣支出、預定避險比例與成本，計算剩餘曝險與台幣壓力。',
      '06 FX / HEDGING', 'hedge-ratio',
      [number('fx-hedge-assets', '外幣資產'), number('fx-hedge-liabilities', '外幣支出／負債'), number('fx-hedge-ratio', '避險比例 %'), number('fx-hedge-fxmove', '匯率壓力 %'), number('fx-hedge-cost', '避險成本 %')],
      ['淨外幣曝險', '避險名目', '未避險壓力', '避險後壓力'],
      '避險比例應由未來支出、風險承受度、期限與工具條款決定。Forward、期貨與 NDF 的基差、保證金、展期和對手方風險未被簡化模型消除。',
      '淨曝險＝資產−負債；避險名目＝淨曝險×比例；未避險壓力＝淨曝險×匯率變動；避險後壓力＝剩餘曝險×匯率變動＋避險成本。',
      '使用者資產／負債紀錄與銀行避險報價'),
    T('forex-margin-risk', 'forex-margin-risk.html', 'forex.html', 'forex-risk', 'forex', '保證金風控',
      '外匯槓桿、保證金與 Stop-out 緩衝計算器', '輸入帳戶、名目部位、槓桿、維持保證金與壓力波動，計算距離強平的緩衝。',
      '06 FX / LEVERAGE & RISK', 'margin-risk',
      [number('fx-margin-equity', '帳戶權益'), number('fx-margin-notional', '名目部位'), number('fx-margin-leverage', '槓桿倍數'), number('fx-margin-maintenance', '維持保證金 %'), number('fx-margin-shock', '不利波動 %')],
      ['初始保證金', '壓力損失', '壓力後權益', '保證金緩衝'],
      '槓桿允許的名目部位不是可承受損失。Stop-out 門檻、滑價、週末跳空與負餘額政策要以你的平台條款為準。',
      '初始保證金＝名目部位÷槓桿；壓力損失＝名目部位×不利波動；維持門檻＝名目部位×維持保證金率。',
      '使用者交易平台條款／實際帳戶條件'),

    T('commodity-carry', 'commodity-carry.html', 'commodities.html', 'commodities-foundation', 'commodities', '現貨與展期',
      '商品現貨、期貨展期與抵押品收益拆解器', '輸入現貨、近月／遠月價格與持有天數，估算商品產品的方向報酬與展期影響。',
      '07 COMMODITIES / FOUNDATION', 'commodity-carry',
      [number('comm-spot', '現貨價格'), number('comm-front', '近月期貨價格'), number('comm-next', '遠月期貨價格'), number('comm-days', '合約間隔天數', step='1'), number('comm-fee', '費用與交易摩擦 %')],
      ['近月基差', '年化展期率', '費後展期', '曲線狀態'],
      '商品 ETF／期貨不等於現貨。請填入同一商品、同一時間取得的合約價格；換月規則、乘數、保證金和抵押品收益應以產品文件核對。',
      '基差＝近月÷現貨−1；簡化展期率＝(遠月÷近月−1)×365/天數；正值通常代表 contango，負值通常代表 backwardation。',
      '使用者交易所／產品文件／公開合約報價'),
    T('commodity-allocation', 'commodity-allocation.html', 'commodities.html', 'commodities-metrics', 'commodities', '商品配置',
      '商品配置、波動與組合風險預算工具', '輸入黃金、能源、農產品與其他實際部位，檢查集中度及單一商品對總組合的壓力。',
      '07 COMMODITIES / METRICS', 'commodity-allocation',
      [number('comm-alloc-total', '組合總資產'), number('comm-alloc-gold', '黃金部位'), number('comm-alloc-energy', '能源部位'), number('comm-alloc-agri', '農產品部位'), number('comm-alloc-other', '其他商品部位'), number('comm-alloc-shock', '壓力跌幅 %')],
      ['商品占比', '最大商品占比', '壓力損失', '壓力後組合'],
      '商品配置的功能可能是通膨、危機或週期曝險；請使用實際市值與事先設定的壓力幅度，不把歷史相關性當成保證。',
      '商品占比＝商品總市值÷組合總資產；壓力損失＝商品總市值×壓力跌幅；最大商品占比為四類中的最大者。',
      '使用者資產紀錄／產品文件'),
    T('commodity-seasonality', 'commodity-seasonality.html', 'commodities.html', 'commodities-practice', 'commodities', '商品季節性',
      '商品公開價格季節性與月報酬分析儀', '抓取 Yahoo 公開商品期貨日線，按月份整理歷史平均報酬與正報酬比例，不將季節性當作預測。',
      '07 COMMODITIES / PRACTICE', 'yahoo-seasonality',
      [text('comm-season-symbol', '商品期貨代號', 'GC=F', '例如 GC=F、CL=F、SI=F')],
      ['最新價格', '樣本年數', '最佳月份', '最大月跌幅'],
      '季節性統計會受到樣本期間、換月、美元、庫存與供需衝擊影響。工具使用公開連續序列作教育分析，不代表可直接交易。',
      '月報酬＝當月最後價格÷上月最後價格−1；最佳月份以樣本平均報酬排序，並同時呈現樣本數。',
      'Yahoo Finance chart 公開商品期貨歷史行情'),
    T('commodity-hedge-breakeven', 'commodity-hedge-breakeven.html', 'commodities.html', 'commodities-risk', 'commodities', '商品避險損益',
      '商品曝險與避險損益平衡工具', '輸入實際商品曝險、避險名目、基差變動與成本，檢查避險後的淨壓力損益。',
      '07 COMMODITIES / RISK', 'commodity-hedge',
      [number('comm-hedge-exposure', '商品曝險市值'), number('comm-hedge-ratio', '避險比例 %'), number('comm-hedge-move', '商品價格變動 %'), number('comm-hedge-basis', '基差變動 %'), number('comm-hedge-cost', '避險成本 %')],
      ['現貨損益', '避險損益', '基差損益', '淨結果'],
      '避險可能把方向風險換成基差、展期、流動性與合約風險。請使用實際合約乘數和避險名目，並確認商品 ETF 與現貨的追蹤差異。',
      '現貨損益＝曝險×價格變動；避險損益取反向方向×避險名目；淨結果再扣基差與成本。',
      '使用者商品曝險／交易所合約／產品文件'),

    T('futures-notional-risk', 'futures-notional-risk.html', 'futures.html', 'futures-foundation', 'futures', '名目與單位風險',
      '期貨乘數、名目價值與停損風險計算器', '輸入實際期貨價格、乘數、口數與停損點數，將看似小幅波動轉成可理解的金額風險。',
      '08 FUTURES / FOUNDATION', 'futures-notional',
      [number('fut-notional-price', '期貨價格'), number('fut-notional-multiplier', '合約乘數'), number('fut-notional-contracts', '口數', step='1'), number('fut-notional-stop', '停損點數'), number('fut-notional-fee', '每口往返成本')],
      ['單口名目價值', '總名目價值', '停損損失', '含費用風險'],
      '期貨保證金只是一種履約擔保，不是最大損失。請以交易所與券商最新合約規格填寫乘數、保證金與費用。',
      '名目價值＝價格×乘數×口數；停損損失＝停損點數×乘數×口數；含費用風險再加雙邊成本。',
      '交易所合約規格／券商費率'),
    T('futures-margin-stress', 'futures-margin-stress.html', 'futures.html', 'futures-metrics', 'futures', '保證金壓力',
      '期貨保證金、追繳與跳空壓力測試器', '輸入帳戶權益、初始／維持保證金與不利點數，估算壓力後保證金覆蓋。',
      '08 FUTURES / METRICS', 'futures-margin',
      [number('fut-margin-equity', '帳戶權益'), number('fut-margin-initial', '初始保證金／口'), number('fut-margin-maintenance', '維持保證金／口'), number('fut-margin-contracts', '口數', step='1'), number('fut-margin-points', '不利點數'), number('fut-margin-multiplier', '合約乘數')],
      ['初始保證金需求', '維持門檻', '壓力後權益', '維持保證金餘額'],
      '追繳規則、盤中風控、跳空與流動性會讓實際處分價格偏離模型。請填入你的交易所／券商條件，工具不假設統一保證金。',
      '壓力損失＝不利點數×乘數×口數；維持餘額＝壓力後權益−維持保證金需求。',
      '交易所／券商保證金表與帳戶條款'),
    T('futures-hedge-ratio', 'futures-hedge-ratio.html', 'futures.html', 'futures-practice', 'futures', '期貨避險口數',
      '現貨曝險與期貨避險口數工具', '用現貨部位、市值、Beta、期貨價格與乘數，估算需要的期貨口數並保留整數化誤差。',
      '08 FUTURES / PRACTICE', 'futures-hedge',
      [number('fut-hedge-spot', '現貨部位市值'), number('fut-hedge-beta', '現貨對指數 Beta'), number('fut-hedge-futures', '期貨價格'), number('fut-hedge-multiplier', '期貨乘數'), number('fut-hedge-ratio', '目標避險比例 %')],
      ['理論避險口數', '整數口數', '未避險名目', '整數化誤差'],
      'Beta 需要用一致期間和基準估算；期貨避險還有基差、到期、轉倉與保證金風險。不要把理論口數當成交保證。',
      '理論口數＝現貨市值×Beta×避險比例÷(期貨價格×乘數)；整數化後重新計算未避險名目。',
      '使用者現貨部位／公開價格／交易所合約規格'),
    T('futures-roll-yield', 'futures-roll-yield.html', 'futures.html', 'futures-risk', 'futures', '轉倉報酬',
      '期貨轉倉成本與期限結構損益工具', '輸入近月、次月合約與持有天數，拆開方向不變時的價格差與年化轉倉影響。',
      '08 FUTURES / RISK', 'futures-roll',
      [number('fut-roll-front', '近月價格'), number('fut-roll-next', '次月價格'), number('fut-roll-days', '合約間隔天數', step='1'), number('fut-roll-notional', '名目部位'), number('fut-roll-cost', '轉倉摩擦 %')],
      ['轉倉差', '年化轉倉率', '名目影響', '費後影響'],
      '連續期貨序列可能在換月時跳動；請確認合約月份、結算方式、乘數與實際轉倉成交，而不是把資料序列當成可直接交易價格。',
      '轉倉差＝次月÷近月−1；年化轉倉率＝轉倉差×365/天數；費後影響扣除交易摩擦。',
      '交易所合約報價／券商轉倉紀錄'),

    T('options-payoff', 'options-payoff.html', 'options.html', 'options-foundation', 'options', '單腿損益',
      '選擇權單腿到期損益與非線性圖工具', '輸入履約價、權利金、口數與到期標的價格區間，繪製 Call／Put 的損益曲線。',
      '09 OPTIONS / FOUNDATION', 'option-payoff',
      [select('opt-payoff-side', '部位方向', [('call', '買進 Call'), ('put', '買進 Put')]), number('opt-payoff-strike', '履約價'), number('opt-payoff-premium', '權利金／點'), number('opt-payoff-qty', '口數', step='1'), number('opt-payoff-multiplier', '契約乘數'), number('opt-payoff-spot', '目前標的價')],
      ['損益平衡點', '目前到期損益', '最大損失', '盈虧方向'],
      '到期損益圖不是即時估值，也沒有包含時間價值、IV、交易成本與提前平倉。請以實際合約乘數、權利金和部位輸入。',
      'Call 到期損益＝max(S−K,0)−premium；Put 到期損益＝max(K−S,0)−premium；再乘口數與契約乘數。',
      '交易所／券商選擇權契約規格'),
    T('options-breakeven', 'options-breakeven.html', 'options.html', 'options-metrics', 'options', '損益平衡',
      '選擇權權利金、損益平衡與最大風險工具', '用你的多方／空方單腿條件，拆解損益平衡點、最大損失與每一點損益。',
      '09 OPTIONS / METRICS', 'option-breakeven',
      [select('opt-be-side', '部位方向', [('call', '買進 Call'), ('put', '買進 Put'), ('short-call', '賣出 Call'), ('short-put', '賣出 Put')]), number('opt-be-strike', '履約價'), number('opt-be-premium', '權利金／點'), number('opt-be-qty', '口數', step='1'), number('opt-be-multiplier', '契約乘數')],
      ['損益平衡點', '每口權利金', '理論最大損失', '風險型態'],
      '賣方選擇權可能有非線性與尾部損失；最大損失在裸賣 Call 時沒有有限上限。工具只做到期損益，不替代保證金與希臘字母分析。',
      '買 Call BE＝K＋premium；買 Put BE＝K−premium；賣方損益方向相反；最大損失依部位方向與價格上限判斷。',
      '交易所／券商選擇權契約與保證金規則'),
    T('options-black-scholes', 'options-black-scholes.html', 'options.html', 'options-practice', 'options', 'Black–Scholes',
      '選擇權 Black–Scholes 理論價與 Greeks 工具', '輸入標的、履約價、波動率、利率與剩餘天數，計算理論價、Delta、Gamma、Vega 與 Theta。',
      '09 OPTIONS / PRACTICE', 'black-scholes',
      [select('opt-bs-side', '選擇權類型', [('call', 'Call'), ('put', 'Put')]), number('opt-bs-spot', '標的價格'), number('opt-bs-strike', '履約價'), number('opt-bs-vol', '年化波動率 %'), number('opt-bs-rate', '無風險利率 %'), number('opt-bs-days', '剩餘天數', step='1')],
      ['理論權利金', 'Delta', 'Gamma', 'Vega'],
      'Black–Scholes 假設連續交易、固定波動率、無跳躍與歐式行權；實際台指／美式選擇權、股利與市場微結構可能不同。',
      '以 d1、d2 與標準常態分布計算；Vega 以波動率小數單位的價格敏感度呈現。',
      '使用者報價／波動率資料；Black–Scholes 教育公式'),
    T('options-spread', 'options-spread.html', 'options.html', 'options-risk', 'options', '價差策略',
      '選擇權價差策略最大損益與壓力圖工具', '輸入同到期 Bull Call Spread 的兩個履約價與權利金，估算最大獲利、最大損失與到期損益。',
      '09 OPTIONS / RISK', 'option-spread',
      [number('opt-spread-lower', '低履約價'), number('opt-spread-upper', '高履約價'), number('opt-spread-long-premium', '買方權利金'), number('opt-spread-short-premium', '賣方權利金'), number('opt-spread-qty', '口數', step='1'), number('opt-spread-multiplier', '契約乘數'), number('opt-spread-spot', '目前標的價')],
      ['淨權利金', '最大獲利', '最大損失', '損益平衡點'],
      '價差可以限制部分風險，但仍有跳空、流動性、提前指派、保證金與成交價差。此工具只計到期損益，請回查實際合約條款。',
      '淨權利金＝買方權利金−賣方權利金；最大損失＝淨權利金×乘數；最大獲利＝履約價差−淨權利金。',
      '交易所／券商選擇權合約與成交紀錄'),

    T('crypto-wallet-checklist', 'crypto-wallet-checklist.html', 'crypto.html', 'crypto-foundation', 'crypto', '錢包安全',
      '加密資產錢包與私鑰安全檢查表', '逐項確認 seed phrase、硬體錢包、授權、交易所與備份流程，將保管風險轉成可檢查項目。',
      '10 CRYPTO / FOUNDATION', 'checklist',
      [checkbox('crypto-safe-seed', 'seed phrase 已離線保存且無雲端明文'), checkbox('crypto-safe-device', '硬體錢包或設備來源可驗證'), checkbox('crypto-safe-approval', '已檢查並撤銷不必要的 token 授權'), checkbox('crypto-safe-2fa', '交易所已啟用獨立 2FA 與提領白名單'), checkbox('crypto-safe-test', '大額轉帳前完成小額測試'), checkbox('crypto-safe-backup', '備份可由可信任程序復原'), checkbox('crypto-safe-separation', '交易資金與長期保管資金分離'), checkbox('crypto-safe-plan', '已寫下失竊、遺失與帳戶停權應變')],
      ['已完成項目', '完成率', '高風險未完成', '安全提示'],
      '任何勾選表都不能保證鏈上資產安全。不要輸入 seed phrase、私鑰、API secret 或個人認證資料；遇到陌生授權、假客服與高報酬承諾應停止操作。',
      '完成率＝已完成項目÷8；若 seed、2FA、備份或測試任一項未完成，結果會標為高優先風險。',
      '交易所／錢包官方安全文件；本頁不要求敏感資訊'),
    T('crypto-portfolio-risk', 'crypto-portfolio-risk.html', 'crypto.html', 'crypto-metrics', 'crypto', '加密配置',
      '加密資產集中度與波動風險預算器', '輸入你的 BTC、ETH、山寨幣、穩定幣部位與壓力跌幅，量化集中度與組合損失。',
      '10 CRYPTO / METRICS', 'crypto-portfolio',
      [number('crypto-port-total', '加密資產總值'), number('crypto-port-btc', 'BTC 部位'), number('crypto-port-eth', 'ETH 部位'), number('crypto-port-alt', '其他高波動部位'), number('crypto-port-stable', '穩定幣部位'), number('crypto-port-shock', '壓力跌幅 %')],
      ['加密資產占比', '最大部位占比', '壓力損失', '壓力後資產'],
      '請填入你的實際持倉市值；穩定幣仍有發行方、脫鉤、交易所與流動性風險，不能簡化成無風險現金。',
      '部位占比＝各部位÷總值；壓力損失＝高波動部位×跌幅；若穩定幣也設定壓力，應另外輸入保守條件。',
      '使用者錢包／交易所持倉紀錄'),
    T('crypto-liquidation', 'crypto-liquidation.html', 'crypto.html', 'crypto-practice', 'crypto', '清算價格',
      '加密永續合約清算與保證金壓力工具', '輸入實際進場價、槓桿、維持保證金與追加保證金，估算簡化清算價與可承受距離。',
      '10 CRYPTO / PRACTICE', 'crypto-liquidation',
      [select('crypto-liq-side', '方向', [('long', '多單'), ('short', '空單')]), number('crypto-liq-entry', '進場價'), number('crypto-liq-leverage', '槓桿倍數'), number('crypto-liq-maintenance', '維持保證金 %'), number('crypto-liq-extra', '額外保證金'), number('crypto-liq-fee', '預估費用 %')],
      ['簡化清算價', '距離進場 %', '維持保證金', '費用緩衝後距離'],
      '實際清算價還會受標記價格、分層維持保證金、保險基金、資金費率與交易所規則影響。結果是教育近似，不能取代交易所 liquidation calculator。',
      '多單簡化清算價≈進場×(1−1/槓桿＋維持保證金＋費用)；空單方向相反；未含 funding 與階梯保證金。',
      '交易所合約規則／帳戶風控頁'),
    T('crypto-staking-net', 'crypto-staking-net.html', 'crypto.html', 'crypto-risk', 'crypto', '質押淨收益',
      '加密資產質押收益、鎖定期與價格風險工具', '輸入實際質押數量、APY、平台費、鎖定期與價格壓力，查看代幣數量收益不等於法幣收益。',
      '10 CRYPTO / RISK', 'crypto-staking',
      [number('crypto-stake-principal', '質押本金（代幣）'), number('crypto-stake-apy', '年化 APY %'), number('crypto-stake-fee', '平台／驗證者費 %'), number('crypto-stake-days', '鎖定天數', step='1'), number('crypto-stake-price', '目前幣價'), number('crypto-stake-shock', '價格變動 %')],
      ['新增代幣', '費後代幣', '法幣收益壓力', '解鎖前損益'],
      'APY 可能變動，且有智能合約、驗證者、削減、鎖定與流動性風險。請使用官方條款與實際數量，不把 APY 當保證報酬。',
      '費後代幣＝本金×(1＋APY×天數/365×(1−費率))；法幣結果再套用價格變動，未含稅費。',
      '鏈／協議／交易所官方質押條款'),

    T('realestate-rent-buy', 'realestate-rent-buy.html', 'real-estate.html', 'real-estate-foundation', 'real-estate', '租買比較',
      '房地產租屋／購屋現金流比較工具', '輸入你的實際房價、租金、頭期、利率與持有年限，將自住決策拆成現金流與機會成本。',
      '11 REAL ESTATE / FOUNDATION', 'rent-buy',
      [number('re-rb-price', '物件總價'), number('re-rb-down', '頭期款'), number('re-rb-rate', '貸款年利率 %'), number('re-rb-years', '貸款年限', step='1'), number('re-rb-rent', '月租金'), number('re-rb-hold', '比較年數', step='1'), number('re-rb-cost', '持有年費用')],
      ['月供款', '月租金', '持有現金流', '租買差額'],
      '房價、租金、利率與稅費高度在地化。請使用實際銀行條件與租賃市場報價；工具不提供市場房價或升值預測。',
      '本息月付以固定利率攤還；持有現金流＝頭期＋月供×月數＋年費用×年數；租屋現金流＝月租×月數。',
      '使用者銀行報價／租約／物件文件'),
    T('realestate-amortization', 'realestate-amortization.html', 'real-estate.html', 'real-estate-metrics', 'real-estate', '房貸攤還',
      '房貸本息攤還、利息與提前還款工具', '用實際貸款本金、年利率、期限與額外還款，計算月付與剩餘期數。',
      '11 REAL ESTATE / METRICS', 'amortization',
      [number('re-am-principal', '貸款本金'), number('re-am-rate', '年利率 %'), number('re-am-years', '原始年限', step='1'), number('re-am-extra', '每月額外還款'), number('re-am-fee', '提前還款費用')],
      ['原始月付', '總利息', '提前後月數', '節省利息'],
      '本息攤還不包含寬限期、浮動利率重設、保險、稅費與提前清償限制。請以銀行攤還表交叉核對。',
      '月付＝P×r(1+r)^n÷((1+r)^n−1)；額外還款需逐月重算本金，實際銀行規則可能不同。',
      '使用者銀行貸款契約／攤還表'),
    T('realestate-vacancy-stress', 'realestate-vacancy-stress.html', 'real-estate.html', 'real-estate-practice', 'real-estate', '空置壓力',
      '出租物件空置、費用與 DSCR 壓力測試器', '輸入你的月租、空置率、營運費用、債務服務與準備金，觀察出租現金流的安全邊際。',
      '11 REAL ESTATE / PRACTICE', 'vacancy-stress',
      [number('re-vac-rent', '月租金'), number('re-vac-occupancy', '出租率 %'), number('re-vac-expense', '營運費用率 %'), number('re-vac-debt', '月債務服務'), number('re-vac-reserve', '每月修繕／準備金')],
      ['有效月收入', 'NOI', 'DSCR', '月現金流'],
      '出租率、費用與修繕應以租約、歷史帳務與保守假設建立；DSCR 小於 1 代表營運收入不足覆蓋債務服務，不是單一投資結論。',
      '有效收入＝月租×出租率；NOI＝有效收入×(1−費用率)−準備金；DSCR＝NOI÷債務服務。',
      '使用者租約／物業帳務／銀行條件'),
    T('realestate-exit-cost', 'realestate-exit-cost.html', 'real-estate.html', 'real-estate-risk', 'real-estate', '退出成本',
      '房地產出售成本、剩餘貸款與淨回收工具', '輸入買入價、目前成交估值、出售費用、稅費與剩餘貸款，拆解退出後真正可回收資金。',
      '11 REAL ESTATE / RISK', 'exit-cost',
      [number('re-exit-buy', '買入總成本'), number('re-exit-current', '目前可查證估值'), number('re-exit-cost', '出售費用率 %'), number('re-exit-tax', '稅費與其他支出'), number('re-exit-loan', '剩餘貸款'), number('re-exit-improve', '裝修／改善成本')],
      ['出售淨額', '投入總額', '名目損益', '投入報酬率'],
      '目前估值必須來自可查證交易、估價或市場比較，不由工具自動生成。稅務、仲介、清償、裝修與時間價值需按所在地規則核對。',
      '出售淨額＝目前估值×(1−出售費用率)−稅費−剩餘貸款；名目損益＝出售淨額−買入與改善總成本。',
      '使用者成交／估價／貸款與稅費文件'),

    T('macro-inflation-purchasing', 'macro-inflation-purchasing.html', 'macro-economics.html', 'macro-economics-foundation', 'macro', '通膨購買力',
      '通膨、實質報酬與購買力換算工具', '輸入你要規劃的金額、通膨率與年限，將名目金額換算成實質購買力與需要的未來金額。',
      '12 MACRO / FOUNDATION', 'inflation-purchasing',
      [number('macro-inf-amount', '目前金額'), number('macro-inf-rate', '年通膨率 %'), number('macro-inf-years', '年數', step='1'), number('macro-inf-return', '名目年化報酬 %')],
      ['未來名目需求', '實質購買力', '名目報酬', '實質報酬'],
      '通膨率不是固定不變，CPI 也不等於每個人的生活成本。請把自己的支出籃子、期限與可查證 CPI 口徑分開處理。',
      '未來需求＝目前金額×(1＋通膨率)^年數；實質購買力＝目前金額÷(1＋通膨率)^年數；實質報酬≈(1＋名目報酬)/(1＋通膨率)−1。',
      '使用者預算；CPI 口徑回查官方統計'),
    T('macro-recession-dashboard', 'macro-recession-dashboard.html', 'macro-economics.html', 'macro-economics-metrics', 'macro', '總經公開序列',
      '失業率、殖利率利差與 CPI 公開總經儀表板', '抓取 FRED 公開序列，並列顯示失業率、10Y−2Y 與 CPI 年增，保留日期與缺值狀態。',
      '12 MACRO / METRICS', 'fred-recession',
      [],
      ['最新失業率', '最新 10Y−2Y', 'CPI YoY', '觀測日期'],
      '宏觀序列具有不同頻率、修訂與發布延遲。工具只顯示公開觀測與透明同比／利差，不把三個序列合併成精準衰退預測。',
      'CPI YoY＝CPI_t÷CPI_{t−12}−1；10Y−2Y＝DGS10−DGS2；失業率保留 FRED 原始百分比。',
      'FRED UNRATE／DGS2／DGS10／CPIAUCSL'),
    T('macro-rate-shock', 'macro-rate-shock.html', 'macro-economics.html', 'macro-economics-practice', 'macro', '利率衝擊',
      '利率變動對資產配置的敏感度工具', '輸入你的債券、股票估值或貸款曝險與久期／敏感度，估算升降息的第一階影響。',
      '12 MACRO / PRACTICE', 'macro-rate-shock',
      [number('macro-shock-bond', '債券市值'), number('macro-shock-duration', '債券久期'), number('macro-shock-equity', '股票估值曝險'), number('macro-shock-equity-sens', '股票利率敏感度 %／1%'), number('macro-shock-rate', '利率變動 bp'), number('macro-shock-loan', '浮動利率貸款餘額')],
      ['債券價格影響', '股票估值影響', '貸款利息影響', '合計壓力'],
      '不同資產對利率的敏感度不是固定常數；請使用你的持倉久期、估值假設與貸款條件，結果是第一階壓力測試。',
      '債券影響≈−市值×久期×利率變動；股票影響＝股票曝險×敏感度×利率變動；貸款利息影響＝貸款餘額×利率變動。',
      '使用者資產／貸款紀錄；基金月報久期'),
    T('macro-regime-quadrant', 'macro-regime-quadrant.html', 'macro-economics.html', 'macro-economics-risk', 'macro', '成長通膨象限',
      '成長／通膨四象限與資產偏重檢查器', '輸入可查證的成長、通膨及其方向變化，將目前研究假設放入象限並列出需要交叉驗證的風險。',
      '12 MACRO / RISK', 'macro-quadrant',
      [select('macro-q-growth', '成長狀態', [('up', '改善'), ('down', '惡化')]), select('macro-q-inflation', '通膨狀態', [('up', '上升'), ('down', '下降')]), number('macro-q-growth-rate', '成長數值或變化 %'), number('macro-q-inflation-rate', '通膨數值或變化 %')],
      ['目前象限', '成長輸入', '通膨輸入', '資料完整度'],
      '四象限是整理研究假設的溝通工具，不是資產配置自動答案。請以 GDP、就業、CPI、實質利率、信用與盈利等原始序列交叉驗證。',
      '成長改善＋通膨下降＝Goldilocks；成長改善＋通膨上升＝Overheating；成長惡化＋通膨上升＝Stagflation；成長惡化＋通膨下降＝Disinflation。',
      'FRED／央行／官方統計；象限分類為教育框架'),

    T('strategy-rule-backtest', 'strategy-rule-backtest.html', 'trading-strategy.html', 'technical-system', 'strategy', '規則回測',
      '均線交叉規則與交易成本回測器', '抓取公開歷史價格，以一根 K 線延遲執行的方式回測快慢均線規則，並扣除你輸入的交易成本。',
      '13 TRADING EXECUTION / PRICE ACTION', 'yahoo-ma-backtest',
      [text('strategy-backtest-symbol', '公開標的代號', 'SPY', '例如 SPY、BTC-USD、0050.TW'), number('strategy-backtest-fast', '快均線天數', step='1'), number('strategy-backtest-slow', '慢均線天數', step='1'), number('strategy-backtest-fee', '單次換手成本 %')],
      ['策略報酬', '買入持有報酬', '最大回撤', '交易次數'],
      '這是簡化規則回測，不是投資建議。執行使用訊號形成後下一根日線報酬，避免直接使用未來收盤；仍未處理停牌、滑價、稅費與 survivorship bias。',
      '訊號＝快均線高於慢均線；部位於下一根觀測生效；策略報酬扣除每次 position change 的成本。',
      'Yahoo Finance chart 公開歷史行情；回測方法透明'),
    T('strategy-trade-journal', 'strategy-trade-journal.html', 'trading-strategy.html', 'risk-expectancy', 'strategy', '交易日誌',
      '交易日誌 R 倍數、期望值與損益平衡工具', '以你的真實交易紀錄摘要計算勝率、平均 R、成本後期望值與損益平衡勝率。',
      '13 TRADING EXECUTION / EXPECTANCY', 'trade-journal',
      [number('strategy-journal-wins', '獲利筆數', step='1'), number('strategy-journal-losses', '虧損筆數', step='1'), number('strategy-journal-avgwin', '平均獲利 R'), number('strategy-journal-avgloss', '平均虧損 R'), number('strategy-journal-cost', '每筆成本 R')],
      ['勝率', '成本後期望值', '損益平衡勝率', 'Profit factor'],
      '請從自己的已結束交易日誌輸入統計，不要把示範數字當成策略結果。樣本數、選股偏誤、滑價與未實現損益都會影響結論。',
      '期望值＝勝率×平均獲利−虧損率×平均虧損−成本；損益平衡勝率＝(平均虧損＋成本)÷(平均獲利＋平均虧損)。',
      '使用者交易日誌；R 倍數定義由交易計畫固定'),
    T('strategy-pair-spread', 'strategy-pair-spread.html', 'trading-strategy.html', 'pair-trading', 'strategy', '配對價差',
      '配對交易價差、相關係數與 Z-score 工具', '抓取兩個公開標的的歷史價格，計算標準化價差、相關係數與偏離程度，保留均值回歸失效風險。',
      '13 TRADING EXECUTION / PAIR & SPREAD', 'yahoo-pair-spread',
      [text('strategy-pair-a', '標的 A', 'SPY', '例如 SPY、2330.TW'), text('strategy-pair-b', '標的 B', 'QQQ', '例如 QQQ、2454.TW'), number('strategy-pair-window', 'Z-score 窗口', step='1')],
      ['相關係數', '目前 Z-score', '價差均值', '最大價差偏離'],
      '相關係數不是協整證明。真正配對策略要處理 hedge ratio、借券、交易成本、結構變化與樣本外驗證；工具只提供研究起點。',
      '標準化價差＝A 的 normalized price−B 的 normalized price；Z＝(價差−窗口平均)÷窗口標準差。',
      'Yahoo Finance chart 公開歷史行情；研究結果非交易訊號'),
    T('strategy-grid-risk', 'strategy-grid-risk.html', 'trading-strategy.html', 'grid-mechanics', 'strategy', '網格風險',
      '網格單格利潤、費用與破網風險工具', '輸入你的網格上下限、格數、投入資金、當前價格與費率，檢查單格空間、資金利用率與破網距離。',
      '13 TRADING EXECUTION / GRID MECHANICS', 'grid-risk',
      [number('strategy-grid-lower', '區間下限'), number('strategy-grid-upper', '區間上限'), number('strategy-grid-count', '網格數', step='1'), number('strategy-grid-capital', '投入資金'), number('strategy-grid-price', '目前價格'), number('strategy-grid-fee', '單邊費率 %')],
      ['單格價差', '費後單格收益', '資金利用率', '破網距離'],
      '網格不是保證套利；單邊趨勢、流動性、庫存、手續費與停機規則決定能否存活。請填入你實際打算使用的區間與資金，不使用工具預設行情。',
      '等差單格＝(上限−下限)÷格數；費後收益近似＝單格價差×每格部位−雙邊費用；破網距離取當前價至上下限較近者。',
      '使用者策略參數／交易所費率'),
    T('strategy-position-sizing', 'strategy-position-sizing.html', 'trading-strategy.html', 'position-sizing', 'strategy', '固定風險部位',
      '固定風險、停損滑價與部位大小工具', '輸入帳戶、進場、停損、成本與單筆風險上限，將信心轉換成可承受的股數／口數。',
      '13 TRADING EXECUTION / POSITION SIZING', 'position-sizing',
      [number('strategy-size-capital', '帳戶資金'), number('strategy-size-entry', '進場價'), number('strategy-size-stop', '停損價'), number('strategy-size-risk', '單筆風險 %'), number('strategy-size-cost', '成本與滑價 %')],
      ['風險預算', '每單位風險', '建議數量', '含成本最大損失'],
      '部位大小是風險管理，不是報酬預測。跳空可能使實際損失超過計畫；請把流動性、最小單位、保證金與組合相關性另行納入。',
      '風險預算＝資金×風險比例；每單位風險＝|進場−停損|×(1＋成本率)；數量＝風險預算÷每單位風險向下取整。',
      '使用者交易計畫／券商費率／交易所規格'),
]

assert len(TOOLS) == 49, len(TOOLS)
assert len({tool['file'] for tool in TOOLS}) == len(TOOLS)
assert len({tool['id'] for tool in TOOLS}) == len(TOOLS)
